apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-rate
  namespace: todo-namespace
spec:
  metrics:
  - name: cpu-usage-rate
    initialDelay: 10m
    successCondition: result[0] < 0.50
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1655-prometheus.prometheus.svc.cluster.local:9090
        query: |
          sum(rate(container_cpu_user_seconds_total{namespace='todo-namespace'}[10m])) / sum(machine_cpu_cores) * 100