apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-db
  namespace: todo-namespace
spec:
  serviceName: todo-db-svc
  replicas: 2
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
        - name: postgres
          image: postgres:14
          envFrom:
          - configMapRef:
              name: todo-db-config
          - secretRef:
              name: todo-secrets
          ports:
            - name: web
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi