apiVersion: v1
kind: Service
metadata:
  name: pingpong-db-svc
  namespace: logger-namespace
spec:
  ports:
    - name: psql
      port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: pingpong-db