apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap.yaml
  - manifests/service.yaml
  - manifests/deployment.yaml
images:
  - name: PROJECT/IMAGE
    newName: sokkanen/broadcaster
    newTag: ee7940c5c8d2ad2635b21b8306f0f56292efbcae