apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/namespace.yaml
- manifests/todo_db/configmap.yaml
- manifests/todo_db/service.yaml
- manifests/todo_db/statefulset.yaml
- manifests/backend/configmap.yaml
- manifests/backend/service.yaml
- manifests/backend/secret.yaml
- manifests/backend/deployment.yaml
- manifests/frontend/service.yaml
- manifests/frontend/ingress.yaml
- manifests/frontend/deployment.yaml
images:
- name: PROJECT/IMAGE
  newName: sokkanen/todoapp
  newTag: 785b871c4985190346e3d49a420e0cc7a457135e
