apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/todo_db/configmap.yaml
- manifests/todo_db/service.yaml
- manifests/todo_db/statefulset.yaml
- manifests/configmap.yaml
- manifests/service.yaml
- manifests/analysistemplate.yaml
- manifests/rollout.yaml
- manifests/secret.enc.yaml
images:
- name: PROJECT/IMAGE
  newName: sokkanen/todoapp
  newTag: a03f9360daefae6a9eb2c0943c00ba3b56ccf319
