apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/todo_db/configmap.yaml
- manifests/todo_db/service.yaml
- manifests/todo_db/statefulset.yaml
- manifests/configmap.yaml
- manifests/service.yaml
- manifests/analysistemplate.yaml
- manifests/rollout.yaml
images:
- name: PROJECT/IMAGE
  newName: sokkanen/todoapp
  newTag: 30d1792f2a9a28cb94ab5a52b5e95aa57fe92d44
