apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/todo_db/configmap.yaml
- manifests/todo_db/service.yaml
- manifests/todo_db/statefulset.yaml
- manifests/configmap.yaml
- manifests/service.yaml
- manifests/analysistemplate.yaml
- manifests/rollout.yaml
images:
- name: PROJECT/IMAGE
  newName: sokkanen/todoapp
  newTag: b67bb1c5ec0dbd4ebffb1e0d862f5815a29c8fdf
