apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/todo_db/configmap.yaml
- manifests/todo_db/service.yaml
- manifests/todo_db/statefulset.yaml
- manifests/configmap.yaml
- manifests/service.yaml
- manifests/analysistemplate.yaml
- manifests/rollout.yaml
- manifests/secret.yaml
images:
- name: PROJECT/IMAGE
  newName: sokkanen/todoapp
  newTag: 0f8a1deb253d6720a88bdf8dd3552cbd7a6c30dd
