apiVersion: v1
kind: Service
metadata:
  name: timestamper-svc
spec:
  type: ClusterIP
  selector:
    app: timestamper
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3020