apiVersion: v1
kind: Service
metadata:
  name: todo-db-svc
  namespace: todo-namespace
spec:
  ports:
    - name: psql
      port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: todo-db