apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-dep
  namespace: logger-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
#      volumes:
#        - name: shared-image
#          emptyDir: {}
#        - name: shared-volume
#          persistentVolumeClaim:
#            claimName: volume-claim
      containers:
        - name: logger
          image: sokkanen/logger:206a
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logger-configmap
                  key: message
#          volumeMounts:
#          - name: shared-image
#            mountPath: /app/files
#          - name: shared-volume
#            mountPath: /app/pongs
#        - name: timestamper
#          image: sokkanen/timestamper:110
#          volumeMounts:
#          - name: shared-image
#            mountPath: /app/files