apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-dep
  namespace: logger-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
        - name: logger
          image: sokkanen/logger:401
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /health
               port: 3000
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logger-configmap
                  key: message