apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-dep
  namespace: logger-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
        - name: logger
          image: sokkanen/logger:206a
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logger-configmap
                  key: message