apiVersion: v1
kind: Service
metadata:
  name: logger-svc
  namespace: logger-namespace
spec:
  type: ClusterIP
  selector:
    app: logger
  ports:
    - name: logger-fwd
      port: 2345
      protocol: TCP
      targetPort: 3000