apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
  namespace: todo-namespace
spec:
  replicas: 6
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: PROJECT/IMAGE
          readinessProbe:
            initialDelaySeconds: 10 
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 8080
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 8080
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
          envFrom:
          - configMapRef:
              name: broadcaster-config
          - secretRef:
              name: broadcaster-secrets