apiVersion: v1
kind: Service
metadata:
  name: broadcaster-svc
  namespace: todo-namespace
spec:
  type: ClusterIP
  selector:
    app: broadcaster
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080