apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingpong-db
  namespace: logger-namespace
spec:
  serviceName: pingpong-svc
  replicas: 2
  selector:
    matchLabels:
      app: pingpong-db
  template:
    metadata:
      labels:
        app: pingpong-db
    spec:
      containers:
        - name: postgres
          image: postgres:14
          envFrom:
          - configMapRef:
              name: pingpong-db-config
          - secretRef:
              name: pingpong-secrets
          ports:
            - name: web
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi