apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      volumes:
        - name: shared-image
          emptyDir: {}
      containers:
        - name: logger
          image: sokkanen/logger:110
          volumeMounts:
          - name: shared-image
            mountPath: /app/files
        - name: timestamper
          image: sokkanen/timestamper:110
          volumeMounts:
          - name: shared-image
            mountPath: /app/files