apiVersion: v1
kind: ConfigMap
metadata:
  name: pingpong-config
  namespace: logger-namespace
  labels:
    app: pingpong
data:
  APP_PG_HOST: pingpong-db-svc.logger-namespace
  APP_PG_USER: postgres
  APP_PG_DB: postgres
  APP_PG_PORT: "5432"