apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: logger-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: sokkanen/pingpong:401c
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /health
               port: 3010
          envFrom:
          - configMapRef:
              name: pingpong-config
          - secretRef:
              name: pingpong-secrets