apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: logger-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: sokkanen/pingpong:207a
          envFrom:
          - configMapRef:
              name: pingpong-config
          - secretRef:
              name: pingpong-secrets