apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: logger-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
#      volumes:
#        - name: shared-volume
#          persistentVolumeClaim:
#            claimName: volume-claim
      containers:
        - name: pingpong
          image: sokkanen/pingpong:201
#          volumeMounts:
#          - name: shared-volume
#            mountPath: /app/pongs