apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingpong-hpa
  namespace: logger-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pingpong-dep
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 15