name: gitops todo-app

on:
  push:
    branches:
      - main

env:
  APP_PG_PASSWORD: ${{ secrets.APP_PG_PASSWORD }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  setup-build-publish-deploy-backend:
    name: Setup, Build, Publish, and Deploy Backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: apps/project
          push: true
          tags: sokkanen/todoapp:${{ github.sha }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
      - name: Update yamls
        working-directory: apps/project
        run: |-
          kustomize edit set image PROJECT/IMAGE=sokkanen/todoapp:${{ github.sha }}
      - name: Set secrets
        uses: falnyr/replace-env-vars-action@master
        env:
          APP_PG_PASSWORD: ${{ secrets.APP_PG_PASSWORD }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        with:
          filename: /apps/project/manifests/rollout.yaml

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'apps/project/kustomization.yaml'
          message: New version release for todoapp ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  setup-build-publish-deploy-broadcaster:
    name: Setup, Build, Publish, and Deploy Broadcaster
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: apps/broadcaster
          push: true
          tags: sokkanen/broadcaster:${{ github.sha }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
      - name: Update yamls
        working-directory: apps/broadcaster
        run: |-
          kustomize edit set image PROJECT/IMAGE=sokkanen/broadcaster:${{ github.sha }}
      - name: Set secrets
        uses: falnyr/replace-env-vars-action@master
        env:
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        with:
          filename: /apps/project/manifests/deployment.yaml

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'apps/project/kustomization.yaml'
          message: New version release for broadcaster ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  setup-build-publish-deploy-frontend:
    name: Setup, Build, Publish, and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: apps/project_front
          push: true
          tags: sokkanen/todoapp-ui:${{ github.sha }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
      - name: Update yamls
        working-directory: apps/project_front
        run: |-
          kustomize edit set image PROJECT/IMAGE=sokkanen/todoapp-ui:${{ github.sha }}

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'apps/project/kustomization.yaml'
          message: New version release for todoapp-ui ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}