name: Release todo-application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-a

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true
      - run: |-
          gcloud --quiet auth configure-docker
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Build Backend
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/todoapp:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" \
            ./apps/project
      - name: Publish Backend
        run: |-
          docker push "gcr.io/$PROJECT_ID/todoapp:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
      - name: Deploy Backend
        run: |-
          cd ./apps/project
          kustomize edit set image PROJECT/IMAGE=gcr.io/$PROJECT_ID/todoapp:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment todoapp
          kubectl get services -o wide

      - name: Build UI
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/todoapp-ui:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" \
            ./apps/project_front
      - name: Publish UI
        run: |-
          docker push "gcr.io/$PROJECT_ID/todoapp-ui:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
      - name: Deploy UI
        run: |-
          cd ./apps/project_front
          kustomize edit set image PROJECT/IMAGE=gcr.io/$PROJECT_ID/todoapp-ui:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment todoapp-ui
          kubectl get services -o wide