apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
        - name: todo-ui
          image: sokkanen/todoapp-ui:202a