apiVersion: v1
kind: Service
metadata:
  name: todo-ui-svc
  namespace: todo-namespace
spec:
  type: ClusterIP
  selector:
    app: todo-ui
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8090